version: '3'

services:
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - .:/app
    env_file: ./backend/.env
    ports:
      - 8080:8080
    expose:
      - 8080
    depends_on:
      - database

  fronted:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    working_dir: /app
    env_file: ./backend/.env

  database:
    image: docker.io/mongo:6
    env_file:
      - ./backend/.env
    ports:
      - 27017:27017
    volumes:
      - db-data:/data/db
      - mongo-config:/data/configdb

volumes:
  db-data:
  mongo-config:
