version: '3'

services:
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    volumes:
      - .:/app
    env_file:
      - ./backend/.env
    ports:
      - 8080:8080
    expose:
      - 8080
    depends_on:
      - database

  fronted:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env
    ports:
      - 7000:7000
    expose:
      - 7000

  database:
    image: docker.io/mongo:6
    env_file: 
      .env
    ports:
      - 27017:27017
    volumes:
      - db-data:/data/db
      - mongo-config:/data/configdb

volumes:
  db-data:
  mongo-config:
