apiVersion: apps/v1
kind: Deployment
metadata:
  name: apito-deployment
  labels:
    app: apito
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apito
  template:
    metadata:
      labels:
        app: apito
    spec:
      containers:
        - name: apito
          image:  easbarbosa/apito:latest
          ports:
            - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: apito
  name: apito
spec:
  ports:
    - name: 80-80
      nodePort: 30080
      port: 8888
      protocol: TCP
      targetPort: 8888
  selector:
    app: apito
  type: NodePort
